project:
  type: website
  output-dir: docs

website:
  title: "IntroWebpage"
  navbar:
    left:
      - href: index.html  # Changed from index.qmd to index.html
        text: Home
      - href: about.html  # Added href for about.html
        text: About  # Optionally add text for the About link

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



