project:
  type: website
  output-dir: docs

website:
  title: "IntroWebpage"
  navbar:
    left:
      - href: index.qmd  # Changed from index.qmd to index.html
        text: Home
      - href: about.qmd  # Added href for about.html
        text: About  # Optionally add text for the About link
      - href: Project.qmd  # Link to Projects
        text: Projects  # Display name for the Projects tab

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



